#!/bin/bash
#FD1604#####################################################
snmpwalk -v 2c -c public <ip> .1.3.6.1.4.1.17409.2.8.4.1.1.3 > tmpmac
snmpwalk -v 2c -c public <ip> .1.3.6.1.4.1.17409.2.8.4.1.1.2 > tmpstate
cat tmpmac | awk '{print$1}' |cut -c 33- > tmpid
cat tmpmac | cut -d ":" -f2  | sed s/'\s'//g > tmpmacdone
cat tmpstate | cut -c 33- > tmpstatedone
paste tmpstatedone tmpmacdone | awk '{print "service_description "$0}' > tmpservicendone
paste tmpid tmpservicendone > tmpidmac
cat tmpidmac  | sed 's/= STRING:/ /' | awk '{print$4}' > tmppastestreet
cat tmpidmac  | sed 's/= STRING:/ /' | awk '{print$1" "$2" "$3" "$5}'  > tmppastemac
#paste tmppastemac tmppastestreet > tmpidmac
cat tmpstate | cut -c 33- | awk {'print$1'} | awk '{print "check_command check_snmp!-C public -P 2c -o .1.3.6.1.4.1.17409.2.8.4.1.1.8."$0}' | awk '{print $0"   -r 1"}' > tmpcheckdone
rm olt50gpon.cfg
cat tmpid | while read output
do
echo "define service{" >>  olt50gpon.cfg
echo "        use generic-service" >> olt50gpon.cfg
echo "        host_name    OLT50_description" >> olt50gpon.cfg
cat tmpidmac | grep -w $output | sed 's/= STRING:/ /'| sed 's/"/ /' | sed 's/"/ /' |awk '{print$2" "$3" "$4" "$5" "$6}'|  sed 's/(/ /' | sed 's/)/ /' | sed 's/\,/_/g' | sed 's/\:/_/g' | sed 's/\-/_/g' |  awk '{print tolower($0)}' | sed 's/\"//g'  >> olt50gpon.cfg
cat tmpcheckdone |grep -w $output >> olt50gpon.cfg
echo "        }" >> olt50gpon.cfg
echo "########################################################################################" >> olt50gpon.cfg
done
#rm tmp*
